name: Flutter CI on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # ✅ Windows Runner ব্যবহার হবে

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"  # ✅ তোমার প্রয়োজন অনুযায়ী Flutter ভার্সন সেট করো

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: build/windows/runner/Release/
